name: CI

on:
    push:
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: "3.10"
                cache: "pip"

        - name: Install dependencies
            run: |
                python -m pip install --upgrade pip
                make init

        - name: Run flake8
            run: make flake8

        - name: Run pylint
            run: make pylint

        - name: Run mypy
            run: make mypy-strict

        - name: Test with pytest
            run: make tests
